import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  createPharmacogeneticCapabilityMap,
  evaluateSlco1b1ExactMarker,
  findMarkerObservations,
  parseConsumerDna,
} from "../lib/consumer-dna.mjs";

test("parses a 23andMe header and reports no-calls", () => {
  const report = parseConsumerDna(`# This data file generated by 23andMe\n# build 37\n# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\nrs2\tX\t200\t--`, "genome.txt");
  assert.equal(report.provider, "23andMe");
  assert.equal(report.build.value, "37");
  assert.equal(report.variantRows, 2);
  assert.equal(report.noCalls, 1);
  assert.equal(report.callRate, 0.5);
  assert.deepEqual(report.chromosomes, [{ name: "1", count: 1 }, { name: "X", count: 1 }]);
});

test("parses AncestryDNA allele columns", () => {
  const report = parseConsumerDna(`# AncestryDNA raw data\nrsid\tchromosome\tposition\tallele1\tallele2\nrs9\t2\t300\tA\tG`, "ancestry.txt");
  assert.equal(report.provider, "AncestryDNA");
  assert.equal(report.variantRows, 1);
  assert.equal(report.callRate, 1);
});

test("recognizes an explicit Ancestry-style forward (+) strand declaration", () => {
  const fixtureUrl = new URL("../samples/synthetic-ancestry.txt", import.meta.url);
  const report = parseConsumerDna(readFileSync(fixtureUrl, "utf8"), "synthetic-ancestry.txt");
  const result = evaluateSlco1b1ExactMarker(report);
  assert.equal(report.provider, "AncestryDNA");
  assert.equal(report.orientation.value, "forward");
  assert.equal(report.orientation.evidence, "File header");
  assert.equal(result.status, "supported_observation");
  assert.equal(result.observedGenotype.genotype, "TC");
  assert.deepEqual(result.uncertainty, [
    "Consumer-array calls can contain assay, strand, labeling, or sample errors.",
    "This check does not assess phase, other SLCO1B1 variants, structural variation, or comprehensive pharmacogenomic coverage.",
    "Analytical and clinical confirmation are outside this software's validated scope.",
  ]);

  const hyphenated = parseConsumerDna(`# build 37\n# forward-strand orientation\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "forward-hyphenated.tsv");
  assert.equal(hyphenated.orientation.value, "forward");
  assert.equal(evaluateSlco1b1ExactMarker(hyphenated).status, "supported_observation");
});

test("normalizes AncestryDNA numeric non-autosomal chromosome codes", () => {
  const report = parseConsumerDna(`#This file was generated by AncestryDNA\n#Data was collected using AncestryDNA array version: V2\nrsid\tchromosome\tposition\tallele1\tallele2\nrs230\t23\t1000\tA\tG\nrs240\t24\t1001\tC\tC\nrs250\t25\t1002\tT\tT\nrs260\t26\t1003\tG\tA`, "ancestry-realistic.txt");
  assert.equal(report.provider, "AncestryDNA");
  assert.equal(report.variantRows, 4);
  assert.equal(report.malformedRows, 0);
  assert.deepEqual(report.chromosomes, [
    { name: "X", count: 1 },
    { name: "Y", count: 1 },
    { name: "XY", count: 1 },
    { name: "MT", count: 1 },
  ]);
});

test("does not apply AncestryDNA chromosome codes to an unidentified layout", () => {
  const report = parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\nrs230\t23\t1000\tAG`, "unknown.tsv");
  assert.equal(report.provider, "Generic consumer genotype text");
  assert.equal(report.variantRows, 1);
  assert.equal(report.malformedRows, 1);
});

test("parses quoted comma-separated result files", () => {
  const report = parseConsumerDna(`"RSID","CHROMOSOME","POSITION","RESULT"\n"rs10","3","400","CT"`, "generic.csv");
  assert.equal(report.delimiter, "Comma-separated");
  assert.equal(report.variantRows, 1);
  assert.equal(report.chromosomes[0].name, "3");
});

test("counts duplicate and malformed rows without inventing calls", () => {
  const report = parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\nrs11\t1\t500\tAA\nrs11\t1\t501\tAA\nrs12\t2\tbad\tCC`, "partial.tsv");
  assert.equal(report.variantRows, 2);
  assert.equal(report.duplicateIds, 1);
  assert.equal(report.malformedRows, 1);
});

test("rejects archives and unrelated text clearly", () => {
  assert.throws(() => parseConsumerDna("bytes", "dna.zip"), /Extract the archive locally/);
  assert.throws(() => parseConsumerDna("hello world", "notes.txt"), /could not find consumer-genotype columns/);
});

test("does not count arbitrary genotype text as a valid call", () => {
  const report = parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\nrs20\t1\t600\tBANANA\nrs21\t1\t601\tAG`, "invalid-call.tsv");
  assert.equal(report.variantRows, 1);
  assert.equal(report.malformedRows, 1);
  assert.equal(report.callRate, 1);
});

test("counts a half-missing Ancestry allele pair as a no-call", () => {
  const report = parseConsumerDna(`rsid\tchromosome\tposition\tallele1\tallele2\nrs22\t2\t700\tA\t0`, "partial-call.txt");
  assert.equal(report.variantRows, 1);
  assert.equal(report.noCalls, 1);
  assert.equal(report.callRate, 0);
});

test("rejects unsupported chromosomes and fractional coordinates", () => {
  const report = parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\nrs23\tINVALID\t800\tAA\nrs24\t3\t1.5\tCC\nrs25\tMT\t801\tG`, "invalid-coordinate.tsv");
  assert.equal(report.variantRows, 1);
  assert.equal(report.malformedRows, 2);
  assert.deepEqual(report.chromosomes, [{ name: "MT", count: 1 }]);
});

const supportedHeader = `# Synthetic reference fixture; no real person\n# build 37\n# forward strand\nrsid\tchromosome\tposition\tgenotype`;

test("retains normalized marker facts without retaining raw rows", () => {
  const report = parseConsumerDna(`${supportedHeader}\nRS4149056\t12\t21331549\tTC`, "synthetic-reference.tsv");
  assert.deepEqual(findMarkerObservations(report, "rs4149056"), [{
    rsid: "rs4149056",
    chromosome: "12",
    position: 21331549,
    genotype: "TC",
    noCall: false,
  }]);
  assert.equal(Object.isFrozen(report.markers), true);
  assert.equal("raw" in report.markers[0], false);
});

test("supports only a pinned exact-marker observation and separates its limits", () => {
  const fixtureUrl = new URL("../samples/reference/slco1b1-rs4149056-grch37-forward.tsv", import.meta.url);
  const report = parseConsumerDna(readFileSync(fixtureUrl, "utf8"), "slco1b1-rs4149056-grch37-forward.tsv");
  const result = evaluateSlco1b1ExactMarker(report);
  assert.equal(result.status, "supported_observation");
  assert.equal(result.observedGenotype.genotype, "TC");
  assert.equal(result.validation.status, "input_consistency_checks_passed");
  assert.equal(result.phenotypeMapping.status, "not_performed");
  assert.equal(result.guidelineEvidence.status, "context_only");
  assert.match(result.validation.detail, /not analytical or clinical validation/i);
  assert.match(result.clinicianDiscussion, /before changing treatment/i);

  const capability = createPharmacogeneticCapabilityMap(report);
  assert.equal(capability.exactMarker.status, "supported_observation");
  assert.equal(capability.starAlleles.status, "unavailable");
  assert.equal(capability.complexGenes.status, "unavailable");
});

test("treats a missing locus as unknown and names an appropriate additional test", () => {
  const report = parseConsumerDna(`${supportedHeader}\nrs1\t1\t100\tAA`, "missing.tsv");
  const result = evaluateSlco1b1ExactMarker(report);
  assert.equal(result.status, "abstain");
  assert.equal(result.reasonCode, "marker_missing");
  assert.match(result.validation.detail, /unknown, not a reference or normal call/i);
  assert.match(result.additionalTest, /clinically validated pharmacogenetic test/i);
});

test("abstains when build or strand orientation is ambiguous", () => {
  const noBuild = parseConsumerDna(`# forward strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "no-build.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(noBuild).reasonCode, "unsupported_or_missing_build");

  const noStrand = parseConsumerDna(`# build 37\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "no-strand.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(noStrand).reasonCode, "missing_or_unsupported_orientation");

  const reverse = parseConsumerDna(`# build 37\n# reverse strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tAG`, "reverse.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(reverse).reasonCode, "missing_or_unsupported_orientation");

  const parentheticalReverse = parseConsumerDna(`# build 37\n# genotype is reported on the reverse (-) strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tAG`, "reverse-parenthetical.tsv");
  assert.equal(parentheticalReverse.orientation.value, "reverse");
  assert.equal(evaluateSlco1b1ExactMarker(parentheticalReverse).reasonCode, "missing_or_unsupported_orientation");

  const conflicting = parseConsumerDna(`# build 37\n# forward (+) strand; reverse (-) strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "conflicting-strand.tsv");
  assert.equal(conflicting.orientation.value, null);
  assert.equal(conflicting.orientation.label, "Conflicting strand declarations");
  assert.equal(evaluateSlco1b1ExactMarker(conflicting).reasonCode, "missing_or_unsupported_orientation");
});

test("does not turn negated, prefixed, or compound direction language into a forward declaration", () => {
  for (const declaration of [
    "not forward strand",
    "no forward strand",
    "without a plus strand declaration",
    "non-forward strand",
    "unforward strand",
    "not plus strand",
    "possibly forward strand",
    "reverse-forward strand",
    "reverse / forward strand",
    "minus or plus orientation",
  ]) {
    const report = parseConsumerDna(`# build 37\n# ${declaration}\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, `${declaration}.tsv`);
    assert.equal(report.orientation.value, null, declaration);
    assert.equal(evaluateSlco1b1ExactMarker(report).reasonCode, "missing_or_unsupported_orientation", declaration);
  }
});

test("treats invalid orientation evidence anywhere in a multi-line header as a global abstention", () => {
  for (const comments of [
    ["orientation is unknown", "forward strand"],
    ["no forward strand", "orientation: +"],
    ["forward strand", "orientation is unknown"],
    ["- / + strand"],
    ["maybe + strand"],
    ["forward strand; unknown"],
    ["forward strand. unknown"],
    ["forward strand; not confirmed"],
    ["not; forward strand"],
    [`not ${"filler ".repeat(16)}forward strand`],
    ["perhaps forward strand"],
    ["unknown", "forward strand"],
    ["forward strand?"],
    ["unverified forward strand"],
    ["forward strand remains unverified"],
    ["tentative forward strand"],
    ["provisional forward strand"],
    ["likely forward strand"],
    ["probably forward strand"],
    ["+ strand; provisional"],
  ]) {
    const report = parseConsumerDna(`# build 37\n${comments.map((comment) => `# ${comment}`).join("\n")}\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "ambiguous-orientation.tsv");
    assert.equal(report.orientation.value, null, comments.join(" / "));
    assert.equal(report.orientation.evidence, "File header conflict", comments.join(" / "));
    assert.equal(evaluateSlco1b1ExactMarker(report).reasonCode, "missing_or_unsupported_orientation", comments.join(" / "));
  }
});

test("does not hide late or post-column strand contradictions", () => {
  const lateContradiction = parseConsumerDna(`# build 37\n# forward strand\n# ${"x".repeat(510)} reverse strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "late-contradiction.tsv");
  assert.equal(lateContradiction.orientation.value, null);
  assert.equal(evaluateSlco1b1ExactMarker(lateContradiction).reasonCode, "missing_or_unsupported_orientation");

  const postColumnContradiction = parseConsumerDna(`# build 37\n# forward strand\nrsid\tchromosome\tposition\tgenotype\n# reverse strand\nrs4149056\t12\t21331549\tTC`, "post-column-contradiction.tsv");
  assert.equal(postColumnContradiction.orientation.value, null);
  assert.equal(evaluateSlco1b1ExactMarker(postColumnContradiction).reasonCode, "missing_or_unsupported_orientation");

  assert.throws(
    () => parseConsumerDna(`# ${"x".repeat(16_385)} forward strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "oversized-header.tsv"),
    /header is too large to verify build and strand orientation safely/i,
  );
});

test("rejects invisible or non-ASCII Unicode before it can hide orientation evidence", () => {
  const zeroWidthPrefix = `# build 37\n# forward strand\nrsid\tchromosome\tposition\tgenotype\n\u200B# reverse strand\nrs4149056\t12\t21331549\tTC`;
  const zeroWidthWords = `# build 37\n# forward strand\nrsid\tchromosome\tposition\tgenotype\n# rev\u200Berse str\u200Band\nrs4149056\t12\t21331549\tTC`;
  assert.throws(() => parseConsumerDna(zeroWidthPrefix, "zero-width-prefix.tsv"), /non-ASCII or invisible Unicode formatting/);
  assert.throws(() => parseConsumerDna(zeroWidthWords, "zero-width-words.tsv"), /non-ASCII or invisible Unicode formatting/);

  const leadingBom = parseConsumerDna(`\uFEFF${supportedHeader}\nrs4149056\t12\t21331549\tTC`, "leading-bom.tsv");
  assert.equal(leadingBom.orientation.value, "forward");
  assert.equal(evaluateSlco1b1ExactMarker(leadingBom).status, "supported_observation");
});

test("recognizes bounded symbolic declarations without inferring an unidentified orientation", () => {
  for (const declaration of ["+ strand", "orientation: +", "(+) strand"]) {
    const report = parseConsumerDna(`# build 37\n# ${declaration}\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, `${declaration}.tsv`);
    assert.equal(report.orientation.value, "forward", declaration);
    assert.equal(evaluateSlco1b1ExactMarker(report).status, "supported_observation", declaration);
  }
  for (const declaration of ["- strand", "orientation: -", "(-) strand"]) {
    const report = parseConsumerDna(`# build 37\n# ${declaration}\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tAG`, `${declaration}.tsv`);
    assert.equal(report.orientation.value, "reverse", declaration);
    assert.equal(evaluateSlco1b1ExactMarker(report).reasonCode, "missing_or_unsupported_orientation", declaration);
  }
  const unidentified = parseConsumerDna(`# build 37\n# orientation is unknown\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21331549\tTC`, "unknown-orientation.tsv");
  assert.equal(unidentified.orientation.value, null);
  assert.equal(evaluateSlco1b1ExactMarker(unidentified).reasonCode, "missing_or_unsupported_orientation");
});

test("abstains for duplicate, conflicting, no-call, and coordinate-mismatched target rows", () => {
  const duplicate = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t21331549\tTC\nrs4149056\t12\t21331549\tCT`, "duplicate.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(duplicate).reasonCode, "duplicate_marker");

  const conflict = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t21331549\tTT\nrs4149056\t12\t21331549\tTC`, "conflict.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(conflict).reasonCode, "conflicting_duplicate");

  const noCall = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t21331549\t--`, "no-call.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(noCall).reasonCode, "no_call");

  const wrongCoordinate = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t1\tTC`, "wrong-coordinate.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(wrongCoordinate).reasonCode, "coordinate_mismatch");

  const unexpectedAllele = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t21331549\tAG`, "unexpected-allele.tsv");
  assert.equal(evaluateSlco1b1ExactMarker(unexpectedAllele).reasonCode, "unexpected_allele");
});

test("accepts the independently pinned GRCh38 coordinate", () => {
  const report = parseConsumerDna(`# Synthetic reference fixture\n# GRCh38\n# plus strand\nrsid\tchromosome\tposition\tgenotype\nrs4149056\t12\t21178615\tCC`, "grch38.tsv");
  const result = evaluateSlco1b1ExactMarker(report);
  assert.equal(result.status, "supported_observation");
  assert.equal(result.observedGenotype.build, "38");
});

test("explicitly keeps unsupported complex calls unavailable", () => {
  const report = parseConsumerDna(`${supportedHeader}\nrs4149056\t12\t21331549\tTT`, "synthetic-reference.tsv");
  const result = evaluateSlco1b1ExactMarker(report);
  assert.equal(result.complexCalls.status, "unavailable");
  assert.match(result.complexCalls.detail, /CYP2D6, HLA, copy-number/i);
});

test("rejects VCF, multiple-sample tables, and input over the configured safety limit", () => {
  assert.throws(
    () => parseConsumerDna(`##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n12\t21331549\trs4149056\tT\tC\t.\tPASS\t.\tGT\t0/1`, "sample.vcf"),
    /VCF input is not supported/,
  );
  assert.throws(
    () => parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\tsample_id\nrs1\t1\t100\tAA\tperson-1`, "multi.tsv"),
    /Multiple-sample or repeated genotype columns/,
  );
  assert.throws(
    () => parseConsumerDna("x".repeat(51), "large.txt", { maxCharacters: 50 }),
    /too large to inspect safely/,
  );
  assert.throws(
    () => parseConsumerDna(`rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAA\nrs2\t1\t101\tCC`, "too-many-rows.tsv", { maxVariantRows: 1 }),
    /1-variant in-memory safety limit/,
  );
});
